async function api(url,opt){const r=await fetch(url,opt);if(r.status===401){location.href='index.html';throw 0}return r.json()}
const panel=document.getElementById('panel');
async function boot(){await api('/api/auth/me');const s=await api('/api/admin/stats');document.getElementById('stats').innerHTML=[['Products',s.products],['Designs',s.designs],['Orders',s.orders],['Customers',s.customers]].map(x=>`<div class="summary"><small>${x[0]}</small><h2 style="font-size:30px;margin:8px 0">${x[1]}</h2></div>`).join('');show('orders')}
async function show(type){
 if(type==='orders'){const rows=await api('/api/admin/orders');panel.innerHTML=`<h2>Orders</h2>`+rows.map(o=>{const previews=o.items.map((x,i)=>x.preview?`<a download="${o.order_no}-${i+1}.jpg" href="${x.preview}"><img src="${x.preview}" style="width:70px;height:110px;object-fit:cover;border-radius:8px;margin:4px" alt="final artwork"></a>`:'').join('');return `<article class="summary" style="margin:12px 0"><div style="display:flex;justify-content:space-between;gap:10px"><b>${o.order_no}</b><span>₹${o.total}</span></div><p>${o.name} · ${o.mobile}</p><p>${o.address.house||''}, ${o.address.area||''}, ${o.address.landmark||''}, ${o.address.city||''}, ${o.address.state||''} — ${o.pincode}</p><p>Status: <b>${o.status}</b> · Payment: <b>${o.payment_status}</b></p><div class="actions"><select data-s="${o.id}"><option ${o.status==='new'?'selected':''}>new</option><option ${o.status==='processing'?'selected':''}>processing</option><option ${o.status==='shipped'?'selected':''}>shipped</option><option ${o.status==='delivered'?'selected':''}>delivered</option><option ${o.status==='cancelled'?'selected':''}>cancelled</option></select><select data-p="${o.id}"><option ${o.payment_status==='unpaid'?'selected':''}>unpaid</option><option ${o.payment_status==='paid'?'selected':''}>paid</option><option ${o.payment_status==='refunded'?'selected':''}>refunded</option></select><button class="btn btn-light" onclick="updateOrder(${o.id})">Save</button></div><div>${previews}</div><details><summary>Customization details</summary><pre style="white-space:pre-wrap;font-size:12px">${JSON.stringify(o.items,null,2)}</pre></details></article>`}).join('')||'<p>No orders yet.</p>'}
 else if(type==='products'){const p=await api('/api/products');panel.innerHTML=`<h2>Products</h2><div class="summary"><form id="addProduct" class="fields"><div class="field"><label>Name</label><input name="name" value="Design"></div><div class="field"><label>Price</label><input name="price" type="number" value="200"></div><div class="field"><label>Category</label><input name="category" value="photo"></div><div class="field"><label>Description</label><textarea name="description">A personalized wallet card made to keep a favorite person, moment or memory close.</textarea></div><div class="field"><label>Photo</label><input name="image" type="file" accept="image/*"></div><button class="btn btn-dark">Add product</button></form></div>`+p.map(x=>`<article class="summary" style="margin:12px 0"><b>${x.name}</b><p>₹${x.price} · ${x.category}</p><button class="btn btn-light" onclick="deleteProduct(${x.id})">Delete</button></article>`).join('');document.getElementById('addProduct').onsubmit=async e=>{e.preventDefault();await api('/api/admin/products',{method:'POST',body:new FormData(e.target)});show('products')}}
 else if(type==='designs'){const d=await api('/api/designs');panel.innerHTML=`<h2>Back designs 35–65</h2><div class="summary"><form id="addDesign" class="fields"><div class="field"><label>Design number (35–65)</label><input name="id" type="number" min="35" max="65"></div><div class="field"><label>Design name</label><input name="name"></div><div class="field"><label>Image</label><input name="image" type="file" accept="image/*"></div><button class="btn btn-dark">Save design</button></form></div><div class="design-grid" style="margin-top:16px">`+d.map(x=>`<article class="summary"><b>${x.name}</b><small>${x.image}</small><button class="btn btn-light" onclick="deleteDesign(${x.id})">Delete</button></article>`).join('')+'</div>';document.getElementById('addDesign').onsubmit=async e=>{e.preventDefault();await api('/api/admin/designs',{method:'POST',body:new FormData(e.target)});show('designs')}}
 else if(type==='customers'){panel.innerHTML=`<h2>Customers</h2><div class="field"><label>Search by name or mobile</label><input id="customerSearch" placeholder="Search..."><button class="btn btn-dark" style="margin-top:8px" onclick="loadCustomers()">Search</button></div><div id="customers" style="margin-top:16px"></div>`;loadCustomers()}}
async function loadCustomers(){const q=document.getElementById('customerSearch')?.value||'';const rows=await api('/api/admin/customers?q='+encodeURIComponent(q));document.getElementById('customers').innerHTML=rows.map(c=>`<article class="summary" style="margin:10px 0"><b>${c.name}</b><p>${c.mobile}</p><p>${c.address.house||''}, ${c.address.area||''}, ${c.address.city||''}, ${c.address.state||''} — ${c.pincode}</p></article>`).join('')||'<p>No customers.</p>'}
async function updateOrder(id){const s=document.querySelector(`[data-s="${id}"]`).value,p=document.querySelector(`[data-p="${id}"]`).value;await api('/api/admin/orders/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s,payment_status:p})});show('orders')}
async function deleteProduct(id){if(confirm('Delete product?')){await api('/api/admin/products/'+id,{method:'DELETE'});show('products')}}
async function deleteDesign(id){if(confirm('Delete design '+id+'?')){await api('/api/admin/designs/'+id,{method:'DELETE'});show('designs')}}
document.getElementById('logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='index.html'};boot();
