const qs=new URLSearchParams(location.search);const id=Number(qs.get('design')||1);const price=200;let qty=1,side='front',back=35,photoData=null;const canvas=document.getElementById('preview'),ctx=canvas.getContext('2d');const fields=['name','date','message','request'].map(x=>document.getElementById(x));
const $=id=>document.getElementById(id);function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>e.classList.remove('show'),2200)}
$('productName').textContent=`Design ${String(id).padStart(2,'0')}`;$('price').textContent=price;
async function loadProduct(){try{const r=await fetch(`/api/products/${id}`);if(r.ok){const p=await r.json();$('productName').textContent=p.name||`Design ${String(id).padStart(2,'0')}`;$('price').textContent=p.price||price;$('description').textContent=p.description||$('description').textContent}}catch(e){}}
function fitImage(img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),iw=img.width*s,ih=img.height*s;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih);ctx.restore()}
function drawText(){ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='700 48px DM Sans';ctx.fillText(fields[0].value||'I LOVE YOU',canvas.width/2,canvas.height-210);ctx.font='500 25px DM Sans';ctx.fillText(fields[1].value||'',canvas.width/2,canvas.height-160);ctx.font='400 24px DM Sans';wrap(fields[2].value||'',canvas.width/2,canvas.height-115,canvas.width-100,30)}
function wrap(text,x,y,max,lh){let line='';for(const word of text.split(/\s+/)){const test=line?line+' '+word:word;if(ctx.measureText(test).width>max&&line){ctx.fillText(line,x,y);y+=lh;line=word}else line=test}if(line)ctx.fillText(line,x,y)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#111';ctx.fillRect(0,0,canvas.width,canvas.height);if(side==='front'&&photoData){const img=new Image();img.onload=()=>{fitImage(img,28,28,canvas.width-56,canvas.height-56);drawText()};img.src=photoData}else if(side==='back'){const img=new Image();img.onload=()=>{ctx.drawImage(img,0,0,canvas.width,canvas.height);drawText()};img.onerror=()=>drawText();img.src=`/assets/products/design-${String(back).padStart(2,'0')}.jpg`}else drawText()}
$('photo').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{photoData=reader.result;draw()};reader.readAsDataURL(f)});fields.forEach(e=>e.addEventListener('input',draw));document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{side=b.dataset.side;document.querySelectorAll('[data-side]').forEach(x=>x.classList.toggle('active',x===b));$('frontEditor').classList.toggle('hidden',side!=='front');$('backEditor').classList.toggle('hidden',side!=='back');draw()});
for(let n=35;n<=65;n++){const b=document.createElement('button');b.className='design-option'+(n===35?' active':'');b.innerHTML=`<img src="design-${String(n).padStart(2,'0')}.jpg" alt="Design ${n}" onerror="this.style.opacity='.08'"><span>NO. ${n}</span>`;b.onclick=()=>{back=n;document.querySelectorAll('.design-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()};$('designGrid').appendChild(b)}
$('minus').onclick=()=>{qty=Math.max(1,qty-1);$('quantity').textContent=qty};$('plus').onclick=()=>{qty++;$('quantity').textContent=qty};
function item(){return{id,productName:$('productName').textContent,unitPrice:Number($('price').textContent)||price,quantity:qty,frontPhoto:photoData,backDesign:back,name:fields[0].value,date:fields[1].value,message:fields[2].value,request:fields[3].value,preview:canvas.toDataURL('image/jpeg',.82)}}function save(){localStorage.setItem('twsCart',JSON.stringify([item()]));$('cartCount').textContent=qty}
$('add').onclick=()=>{save();toast('Added to cart')};$('buy').onclick=()=>{save();location.href='checkout.html'};loadProduct();draw();
